name: Deploy Flutter Web to GitHub Pages

on:
  push:
    branches: [ feature/application-about-me ] 
  
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Create .env file
        run: echo "${{ secrets.ENV_FILE }}" > .env
        working-directory: ./application_about_me

      - name: Install dependencies
        run: flutter pub get
        working-directory: ./application_about_me

      - name: Run tests
        run: flutter test
        working-directory: ./application_about_me

      - name: Build Web
        run: |
          flutter build web --release --base-href /flutter-apps/
        working-directory: ./application_about_me
      
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: application_about_me/build/web
